### ISSUE TITLE
Consultation des mesures PM10

### ISSUE THREAD

**Issue by rhum1s** [airpaca/mes2camp#8]
Table différente de celle du NO2
- Quelle table?
- Quelles données?
- Intégration à partir de la fonction graphiques en ajoutant le polluant comme argument ou fonctions séparées?

**Comment by benroc06** [comment]
2 nouvelles vues sont créés 
- pour les PM10  prod.pm10_p904_v2017_dev
- pour les PM2.5 prod.pm25_ma_v2017_dev
idéalement dans le visionnage de l'historique des données distingué en fonction du code campagne (mesure permanente et station virtuelle)

**Comment by rhum1s** [comment]
* Vues des mesures intégrées pour PM.
* Suppression du suffixe dev des nouvelles vues
* Suppression des anciennes tables utilisées pour afficher les points (prod.pm10_p904_2016_v2017, prod.pm25_ma_2016_v2017) et ajout des clauses distinct dans la requête de sélection et de l'année de mesure désirée dans les propriétés du polluant.
* Graphiques selon polluant
